name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  path-to-files:  # id of input
    description: 'Relative path in the repo to the individual function files'
    required: true
    default: './'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'