name: Monday

on:
  issues:
    types: [opened, reopened, closed]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  monday:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'bug')
    steps:
      - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        repository: github/monday-action
        path: actions
        ssh-key: '${{ secrets.MONDAY_DEPLOY_KEY }}'
