name: Monday

on:
  issues:
    types: [opened, reopened, closed]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  monday:
    runs-on: ubuntu-latest
    if: "github.event.label.name = 'bug'"
    steps:
    - name: Hello world
      uses: actions/hello-world-javascript-action@v1
      with:
        who-to-greet: 'Mona the Octocat'
      id: hello

      # This step prints an output (time) from the previous step's action.
    - name: Echo the greeting's time
      run: echo 'The time was ${{ steps.hello.outputs.time }}.'
